spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/subway
      driver-class-name: org.h2.Driver
      username: sa
      password:
  sql:
    init:
      mode: always
